MLIR: lib/Conversion/AsyncToLLVM/AsyncToLLVM.cpp File Reference
AsyncToLLVM.cpp File Reference
#include "mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/StandardOps/Transforms/FuncConversions.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/FormatVariadic.h"
Classes
class YieldOpLowering
Macros
#define DEBUG_TYPE "convert-async-to-llvm"
Functions
static void addAsyncRuntimeApiDeclarations (ModuleOp module)
Adds Async Runtime C API declarations to the module.
static void addLLVMFuncDecl (ModuleOp module, ImplicitLocOpBuilder &builder, StringRef name, LLVM::LLVMType ret, ArrayRef< LLVM::LLVMType > params)
Adds an LLVM function declaration to a module.
static void addCoroutineIntrinsicsDeclarations (ModuleOp module)
Adds coroutine intrinsics declarations to the module.
static void addCRuntimeDeclarations (ModuleOp module)
Adds malloc/free declarations to the module.
static void addResumeFunction (ModuleOp module)
A function that takes a coroutine handle and calls a llvm.coro.resume intrinsics.
static CoroMachinery setupCoroMachinery (FuncOp func)
Builds an coroutine template compatible with LLVM coroutines lowering.
static void addSuspensionPoint (CoroMachinery coro, Value coroState, Operation *op, Block *suspended, Block *resume, OpBuilder &builder)
Add a LLVM coroutine suspension point to the end of suspended block, to resume execution in resume block.
static std::pair< FuncOp, CoroMachinery > outlineExecuteOp (SymbolTable &symbolTable, ExecuteOp execute)
Outline the body region attached to the async.execute op into a standalone function.
Variables
static constexpr const char kAsyncFnPrefix [] = "async_execute_fn"
static constexpr const char * kAddRef = "mlirAsyncRuntimeAddRef"
static constexpr const char * kDropRef = "mlirAsyncRuntimeDropRef"
static constexpr const char * kCreateToken = "mlirAsyncRuntimeCreateToken"
static constexpr const char * kCreateValue = "mlirAsyncRuntimeCreateValue"
static constexpr const char * kCreateGroup = "mlirAsyncRuntimeCreateGroup"
static constexpr const char * kEmplaceToken = "mlirAsyncRuntimeEmplaceToken"
static constexpr const char * kEmplaceValue = "mlirAsyncRuntimeEmplaceValue"
static constexpr const char * kAwaitToken = "mlirAsyncRuntimeAwaitToken"
static constexpr const char * kAwaitValue = "mlirAsyncRuntimeAwaitValue"
static constexpr const char * kAwaitGroup = "mlirAsyncRuntimeAwaitAllInGroup"
static constexpr const char * kExecute = "mlirAsyncRuntimeExecute"
static constexpr const char * kGetValueStorage
static constexpr const char * kAddTokenToGroup
static constexpr const char * kAwaitTokenAndExecute
static constexpr const char * kAwaitValueAndExecute
static constexpr const char * kAwaitAllAndExecute
static constexpr const char * kCoroId = "llvm.coro.id"
static constexpr const char * kCoroSizeI64 = "llvm.coro.size.i64"
static constexpr const char * kCoroBegin = "llvm.coro.begin"
static constexpr const char * kCoroSave = "llvm.coro.save"
static constexpr const char * kCoroSuspend = "llvm.coro.suspend"
static constexpr const char * kCoroEnd = "llvm.coro.end"
static constexpr const char * kCoroFree = "llvm.coro.free"
static constexpr const char * kCoroResume = "llvm.coro.resume"
static constexpr const char * kMalloc = "malloc"
static constexpr const char * kFree = "free"
static constexpr const char * kResume = "__resume"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "convert-async-to-llvm"
Definition at line 26 of file AsyncToLLVM.cpp.
Function Documentation
addAsyncRuntimeApiDeclarations()
static void addAsyncRuntimeApiDeclarations (ModuleOp module) static
Adds Async Runtime C API declarations to the module.
Definition at line 161 of file AsyncToLLVM.cpp.
References mlir::ImplicitLocOpBuilder::atBlockTerminator(), mlir::ImplicitLocOpBuilder::create(), kAddRef, kAddTokenToGroup, kAwaitAllAndExecute, kAwaitGroup, kAwaitToken, kAwaitTokenAndExecute, kAwaitValue, kAwaitValueAndExecute, kCreateGroup, kCreateToken, kCreateValue, kDropRef, kEmplaceToken, kEmplaceValue, kExecute, and kGetValueStorage.
Referenced by YieldOpLowering::matchAndRewrite().
addCoroutineIntrinsicsDeclarations()
static void addCoroutineIntrinsicsDeclarations (ModuleOp module) static
Adds coroutine intrinsics declarations to the module.
Definition at line 217 of file AsyncToLLVM.cpp.
References addLLVMFuncDecl(), kCoroBegin, kCoroEnd, kCoroFree, kCoroId, kCoroResume, kCoroSave, kCoroSizeI64, and kCoroSuspend.
Referenced by YieldOpLowering::matchAndRewrite().
addCRuntimeDeclarations()
static void addCRuntimeDeclarations (ModuleOp module) static
Adds malloc/free declarations to the module.
Definition at line 251 of file AsyncToLLVM.cpp.
References addLLVMFuncDecl(), kFree, and kMalloc.
Referenced by YieldOpLowering::matchAndRewrite().
addLLVMFuncDecl()
static void addLLVMFuncDecl (ModuleOp module, ImplicitLocOpBuilder & builder, StringRef name, LLVM::LLVMType ret, ArrayRef< LLVM::LLVMType > params) static
Adds an LLVM function declaration to a module.
Definition at line 207 of file AsyncToLLVM.cpp.
References mlir::ImplicitLocOpBuilder::create(), and mlir::LLVM::LLVMFunctionType::get().
Referenced by addCoroutineIntrinsicsDeclarations(), and addCRuntimeDeclarations().
addResumeFunction()
static void addResumeFunction (ModuleOp module) static
A function that takes a coroutine handle and calls a llvm.coro.resume intrinsics.
We need this function to be able to pass it to the async runtime execute API.
Definition at line 275 of file AsyncToLLVM.cpp.
References mlir::ImplicitLocOpBuilder::atBlockEnd(), mlir::LLVM::LLVMFunctionType::get(), mlir::LLVM::LLVMIntegerType::get(), mlir::LLVM::LLVMPointerType::get(), kCoroResume, and kResume.
Referenced by YieldOpLowering::matchAndRewrite().
addSuspensionPoint()
static void addSuspensionPoint (CoroMachinery coro, Value coroState, Operation * op, Block * suspended, Block * resume, OpBuilder & builder) static
Add a LLVM coroutine suspension point to the end of suspended block, to resume execution in resume block.
The caller is responsible for creating the two suspended/resume blocks with the desired ops contained in each block. This function merely provides the required control flow logic.
coroState must be a value returned from the call to .coro.save(...) intrinsic (saved coroutine state).
Before:
^bb0: "opBefore"(...) "op"(...) ^cleanup: ... ^suspend: ... ^resume: "op"(...)
After:
^bb0: "opBefore"(...) suspend = llmv.call .coro.suspend(...) switch suspend [-1: ^suspend, 0: ^resume, 1: ^cleanup] ^resume: "op"(...) ^cleanup: ... ^suspend: ...
Definition at line 530 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::edsc::op::eq(), mlir::LLVM::LLVMIntegerType::get(), mlir::Builder::getBoolAttr(), mlir::Operation::getContext(), mlir::Builder::getI8IntegerAttr(), mlir::Operation::getLoc(), mlir::Builder::getSymbolRefAttr(), isZero(), kCoroSuspend, mlir::OpBuilder::setInsertionPointToEnd(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by outlineExecuteOp().
outlineExecuteOp()
static std::pair<FuncOp, CoroMachinery> outlineExecuteOp (SymbolTable & symbolTable, ExecuteOp execute) static
Outline the body region attached to the async.execute op into a standalone function.
Note that this is not reversible transformation.
Definition at line 580 of file AsyncToLLVM.cpp.
References addSuspensionPoint(), mlir::ImplicitLocOpBuilder::atBlockTerminator(), mlir::Location::cast(), mlir::ImplicitLocOpBuilder::create(), mlir::OpBuilder::create(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::IntegerType::get(), mlir::FunctionType::get(), mlir::LLVM::LLVMPointerType::get(), mlir::Operation::getBlock(), mlir::Builder::getContext(), mlir::Operation::getContext(), mlir::Type::getContext(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::OpBuilder::getListener(), mlir::Operation::getLoc(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::getUsedValuesDefinedAbove(), mlir::SymbolTable::insert(), mlir::Type::isa(), kAddRef, kAddTokenToGroup, kAsyncFnPrefix, kAwaitAllAndExecute, kAwaitGroup, kAwaitToken, kAwaitTokenAndExecute, kAwaitValue, kAwaitValueAndExecute, kCoroSave, kCreateGroup, kDropRef, kExecute, kGetValueStorage, kResume, mlir::BlockAndValueMapping::map(), mlir::SymbolTable::Private, mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToStart(), mlir::SymbolTable::setSymbolVisibility(), setupCoroMachinery(), mlir::Block::splitBlock(), mlir::ConversionPatternRewriter::splitBlock(), and mlir::success().
Referenced by YieldOpLowering::matchAndRewrite().
setupCoroMachinery()
static CoroMachinery setupCoroMachinery (FuncOp func) static
Builds an coroutine template compatible with LLVM coroutines lowering.
entry block sets up the coroutine.
cleanup block cleans up the coroutine state.
`suspend block after the .coro.end() defines what value will be returned to the initial caller of a coroutine. Everything before the .coro.end() will be executed at every suspension point.
Coroutine structure (only the important bits):
func (<function-arguments>) -> (!async.token, !async.value<T>) { ^entryBlock(<function-arguments>): token = <async token>=""> : !async.token // create async runtime token value = <async value>=""> : !async.value<T> // create async value hdl = llvm.call .coro.id(...) // create a coroutine handle br ^cleanup
^cleanup: llvm.call .coro.free(...) // delete coroutine state br ^suspend
^suspend: llvm.call .coro.end(...) // marks the end of a coroutine return token, value : !async.token, !async.value<T> }
The actual code for the async.execute operation body region will be inserted before the entry block terminator.
Definition at line 360 of file AsyncToLLVM.cpp.
References mlir::ImplicitLocOpBuilder::atBlockBegin(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::LLVM::LLVMIntegerType::get(), mlir::LLVM::LLVMPointerType::get(), kCoroBegin, kCoroEnd, kCoroFree, kCoroId, kCoroSizeI64, kCreateToken, kCreateValue, kFree, and kMalloc.
Referenced by outlineExecuteOp().
Variable Documentation
kAddRef
constexpr const char* kAddRef = "mlirAsyncRuntimeAddRef" static
Definition at line 38 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAddTokenToGroup
constexpr const char* kAddTokenToGroup static
Initial value:
=
    "mlirAsyncRuntimeAddTokenToGroup"
Definition at line 51 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAsyncFnPrefix
constexpr const char kAsyncFnPrefix[] = "async_execute_fn" static
Definition at line 32 of file AsyncToLLVM.cpp.
Referenced by outlineExecuteOp().
kAwaitAllAndExecute
constexpr const char* kAwaitAllAndExecute static
Initial value:
=
    "mlirAsyncRuntimeAwaitAllInGroupAndExecute"
Definition at line 57 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitGroup
constexpr const char* kAwaitGroup = "mlirAsyncRuntimeAwaitAllInGroup" static
Definition at line 47 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitToken
constexpr const char* kAwaitToken = "mlirAsyncRuntimeAwaitToken" static
Definition at line 45 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitTokenAndExecute
constexpr const char* kAwaitTokenAndExecute static
Initial value:
=
    "mlirAsyncRuntimeAwaitTokenAndExecute"
Definition at line 53 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitValue
constexpr const char* kAwaitValue = "mlirAsyncRuntimeAwaitValue" static
Definition at line 46 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitValueAndExecute
constexpr const char* kAwaitValueAndExecute static
Initial value:
=
    "mlirAsyncRuntimeAwaitValueAndExecute"
Definition at line 55 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kCoroBegin
constexpr const char* kCoroBegin = "llvm.coro.begin" static
Definition at line 199 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroEnd
constexpr const char* kCoroEnd = "llvm.coro.end" static
Definition at line 202 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroFree
constexpr const char* kCoroFree = "llvm.coro.free" static
Definition at line 203 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroId
constexpr const char* kCoroId = "llvm.coro.id" static
Definition at line 197 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroResume
constexpr const char* kCoroResume = "llvm.coro.resume" static
Definition at line 204 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and addResumeFunction().
kCoroSave
constexpr const char* kCoroSave = "llvm.coro.save" static
Definition at line 200 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and outlineExecuteOp().
kCoroSizeI64
constexpr const char* kCoroSizeI64 = "llvm.coro.size.i64" static
Definition at line 198 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroSuspend
constexpr const char* kCoroSuspend = "llvm.coro.suspend" static
Definition at line 201 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and addSuspensionPoint().
kCreateGroup
constexpr const char* kCreateGroup = "mlirAsyncRuntimeCreateGroup" static
Definition at line 42 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kCreateToken
constexpr const char* kCreateToken = "mlirAsyncRuntimeCreateToken" static
Definition at line 40 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and setupCoroMachinery().
kCreateValue
constexpr const char* kCreateValue = "mlirAsyncRuntimeCreateValue" static
Definition at line 41 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and setupCoroMachinery().
kDropRef
constexpr const char* kDropRef = "mlirAsyncRuntimeDropRef" static
Definition at line 39 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kEmplaceToken
constexpr const char* kEmplaceToken = "mlirAsyncRuntimeEmplaceToken" static
Definition at line 43 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and YieldOpLowering::matchAndRewrite().
kEmplaceValue
constexpr const char* kEmplaceValue = "mlirAsyncRuntimeEmplaceValue" static
Definition at line 44 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and YieldOpLowering::matchAndRewrite().
kExecute
constexpr const char* kExecute = "mlirAsyncRuntimeExecute" static
Definition at line 48 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kFree
constexpr const char* kFree = "free" static
Definition at line 248 of file AsyncToLLVM.cpp.
Referenced by addCRuntimeDeclarations(), and setupCoroMachinery().
kGetValueStorage
constexpr const char* kGetValueStorage static
Initial value:
=
    "mlirAsyncRuntimeGetValueStorage"
Definition at line 49 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), YieldOpLowering::matchAndRewrite(), and outlineExecuteOp().
kMalloc
constexpr const char* kMalloc = "malloc" static
Definition at line 247 of file AsyncToLLVM.cpp.
Referenced by addCRuntimeDeclarations(), and setupCoroMachinery().
kResume
constexpr const char* kResume = "__resume" static
Definition at line 270 of file AsyncToLLVM.cpp.
Referenced by addResumeFunction(), and outlineExecuteOp().