MLIR: mlir::LLVM::LLVMType Class Reference
mlir::LLVM::LLVMType Class Reference
Base class for LLVM dialect types.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
LLVMDialect & getDialect ()
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static LLVMType getFromOpaquePointer (const void *ptr)
static bool classof (Type type)
Support for isa/cast.
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
Base class for LLVM dialect types.
The LLVM dialect in MLIR fully reflects the LLVM IR type system, prodiving a separate MLIR type for each LLVM IR type. All types are represented as separate subclasses and are compatible with the isa/cast infrastructure.
The LLVM dialect type system is closed: parametric types can only refer to other LLVM dialect types. This is consistent with LLVM IR and enables a more concise pretty-printing format.
Similarly to other MLIR types, LLVM dialect types are owned by the MLIR context, have an immutable identifier (for most types except identified structs, the entire type is the identifier) and are thread-safe.
This class is a thin common base class for different types available in the LLVM dialect. It intentionally does not provide the API similar to llvm::Type to avoid confusion and highlight potentially expensive operations (e.g., type creation in MLIR takes a lock, so it's better to cache types).
Definition at line 70 of file LLVMTypes.h.
Member Function Documentation
classof()
bool LLVMType::classof (Type type) static
Support for isa/cast.
Definition at line 31 of file LLVMTypes.cpp.
References mlir::Type::getDialect().
getDialect()
LLVMDialect & LLVMType::getDialect ()
Definition at line 35 of file LLVMTypes.cpp.
References mlir::Type::getDialect().
getFromOpaquePointer()
static LLVMType mlir::LLVM::LLVMType::getFromOpaquePointer (const void * ptr) inline static
Definition at line 77 of file LLVMTypes.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::LLVM::LLVMType >::getFromVoidPointer().
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp