MLIR: YieldOpLowering Class Reference
YieldOpLowering Class Reference
Public Member Functions
YieldOpLowering (TypeConverter &converter, MLIRContext *ctx, const llvm::DenseMap< FuncOp, CoroMachinery > &outlinedFunctions)
LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::ConversionPattern
virtual void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Additional Inherited Members
Protected Member Functions inherited from mlir::ConversionPattern
ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter &typeConverter, MLIRContext *ctx)
Construct a conversion pattern that matches an operation with the given root name.
ConversionPattern (PatternBenefit benefit, TypeConverter &typeConverter, MatchAnyOpTypeTag tag)
Construct a conversion pattern that matches any operation type.
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Protected Attributes inherited from mlir::ConversionPattern
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
Definition at line 982 of file AsyncToLLVM.cpp.
Constructor & Destructor Documentation
YieldOpLowering()
YieldOpLowering::YieldOpLowering (TypeConverter & converter, MLIRContext * ctx, const llvm::DenseMap< FuncOp, CoroMachinery > & outlinedFunctions) inline explicit
Definition at line 984 of file AsyncToLLVM.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult YieldOpLowering::matchAndRewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline override
Definition at line 992 of file AsyncToLLVM.cpp.
References addAsyncRuntimeApiDeclarations(), mlir::TypeConverter::addConversion(), addCoroutineIntrinsicsDeclarations(), addCRuntimeDeclarations(), addResumeFunction(), mlir::WalkResult::advance(), mlir::applyPartialConversion(), mlir::Type::cast(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::Operation::emitOpError(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::LLVM::LLVMPointerType::get(), mlir::Builder::getContext(), mlir::Operation::getLoc(), mlir::Value::getType(), mlir::OwningRewritePatternList::insert(), mlir::WalkResult::interrupt(), kEmplaceToken, kEmplaceValue, kGetValueStorage, outlineExecuteOp(), mlir::populateCallOpTypeConversionPattern(), mlir::populateFuncOpTypeConversionPattern(), mlir::success(), and mlir::WalkResult::wasInterrupted().
The documentation for this class was generated from the following file:
lib/Conversion/AsyncToLLVM/AsyncToLLVM.cpp