MLIR: mlir::python::PyAffineMap Class Reference
mlir::python::PyAffineMap Class Reference
#include "Bindings/Python/IRModules.h"
Public Member Functions
PyAffineMap (PyMlirContextRef contextRef, MlirAffineMap affineMap)
bool operator== (const PyAffineMap &other)
operator MlirAffineMap () const
MlirAffineMap get () const
pybind11::object getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineMap.
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyAffineMap createFromCapsule (pybind11::object capsule)
Creates a PyAffineMap from the MlirAffineMap wrapped by a capsule.
Detailed Description
Definition at line 671 of file IRModules.h.
Constructor & Destructor Documentation
PyAffineMap()
mlir::python::PyAffineMap::PyAffineMap (PyMlirContextRef contextRef, MlirAffineMap affineMap) inline
Definition at line 673 of file IRModules.h.
References mlir::operator==().
Member Function Documentation
createFromCapsule()
PyAffineMap PyAffineMap::createFromCapsule (pybind11::object capsule) static
Creates a PyAffineMap from the MlirAffineMap wrapped by a capsule.
Note that PyAffineMap instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirAffineMap is taken by calling this function.
Definition at line 2725 of file IRModules.cpp.
References mlir::python::PyInsertionPoint::atBlockBegin(), mlir::python::PyInsertionPoint::atBlockTerminator(), MlirNamedAttribute::attribute, mlir::python::PyMlirContext::contextEnter(), mlir::python::PyLocation::contextEnter(), mlir::python::PyInsertionPoint::contextEnter(), mlir::python::PyMlirContext::contextExit(), mlir::python::PyLocation::contextExit(), mlir::python::PyInsertionPoint::contextExit(), mlir::python::PyOperation::create(), createCustomDialectWrapper(), mlir::python::PyMlirContext::createFromCapsule(), mlir::python::PyLocation::createFromCapsule(), mlir::python::PyModule::createFromCapsule(), mlir::python::PyAttribute::createFromCapsule(), mlir::python::PyType::createFromCapsule(), mlir::python::PyMlirContext::createNewContextForInit(), mlir::python::PyOperation::createOpView(), MlirStringRef::data, mlir::python::PyMlirContext::forContext(), mlir::python::PyModule::forModule(), mlir::python::PyOperation::forOperation(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::PyRegion::get(), mlir::python::PyBlock::get(), mlir::python::PyValue::get(), mlir::python::PyOperationBase::getAsm(), mlir::PyPrintAccumulator::getCallback(), mlir::python::PyMlirContext::getCapsule(), mlir::python::PyLocation::getCapsule(), mlir::python::PyModule::getCapsule(), mlir::python::PyAttribute::getCapsule(), mlir::python::PyType::getCapsule(), getCapsule(), mlir::python::BaseContextObject::getContext(), mlir::python::PyThreadContextEntry::getDefaultContext(), mlir::python::PyThreadContextEntry::getDefaultInsertionPoint(), mlir::python::PyThreadContextEntry::getDefaultLocation(), mlir::python::PyMlirContext::getLiveCount(), mlir::python::PyMlirContext::getLiveModuleCount(), mlir::python::PyMlirContext::getLiveOperationCount(), mlir::python::PyOperationBase::getOperation(), mlir::python::PyOpView::getOperationObject(), mlir::PyPrintAccumulator::getUserData(), mlir::python::PyInsertionPoint::insert(), mlir::PyPrintAccumulator::join(), kContextGetFileLocationDocstring, kContextParseTypeDocstring, kDumpDocstring, kModuleParseDocstring, kOperationCreateDocstring, kOperationGetAsmDocstring, kOperationPrintDocstring, kOperationStrDunderDocstring, kValueDunderStrDocstring, MlirStringRef::length, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapGetContext(), mlirAffineMapIsNull(), mlirAttributeDump(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeIsNull(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBlockGetFirstOperation(), mlirBlockPrint(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextSetAllowUnregisteredDialects(), mlirDialectGetNamespace(), mlirDialectIsNull(), mlirIdentifierStr(), mlirLocationEqual(), mlirLocationFileLineColGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleGetBody(), mlirModuleGetOperation(), mlirModuleIsNull(), mlirOperationDump(), mlirOperationGetName(), mlirOperationGetNumResults(), mlirOperationGetResult(), mlirOperationPrint(), mlirOperationVerify(), mlirPythonCapsuleToAffineMap(), mlirRegionGetFirstBlock(), mlirTypeDump(), mlirTypeIsNull(), mlirTypeParseGet(), mlirTypePrint(), mlirValueDump(), mlirValueGetType(), mlirValuePrint(), MlirNamedAttribute::name, mlir::python::PyNamedAttribute::namedAttr, mlir::PyPrintAccumulator::parts, mlir::python::populateIRSubmodule(), mlir::python::PyOperationBase::print(), mlir::python::PyNamedAttribute::PyNamedAttribute(), mlir::python::PyObjectRef< T >::releaseObject(), mlir::python::SetPyError(), and toMlirStringRef().
get()
MlirAffineMap mlir::python::PyAffineMap::get () const inline
Definition at line 677 of file IRModules.h.
References mlir::python::populateIRSubmodule().
getCapsule()
py::object PyAffineMap::getCapsule ()
Gets a capsule wrapping the void* within the MlirAffineMap.
Definition at line 2721 of file IRModules.cpp.
References mlirPythonAffineMapToCapsule().
Referenced by createFromCapsule().
operator MlirAffineMap()
mlir::python::PyAffineMap::operator MlirAffineMap () const inline
Definition at line 676 of file IRModules.h.
operator==()
bool PyAffineMap::operator== (const PyAffineMap & other)
Definition at line 2717 of file IRModules.cpp.
References mlirAffineMapEqual().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModules.h
lib/Bindings/Python/IRModules.cpp