MLIR: lib/Dialect/SPIRV/Transforms/DecorateCompositeTypeLayoutPass.cpp File Reference
DecorateCompositeTypeLayoutPass.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/Passes.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static void populateSPIRVLayoutInfoPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Function Documentation
populateSPIRVLayoutInfoPatterns()
static void populateSPIRVLayoutInfoPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx) static
Definition at line 77 of file DecorateCompositeTypeLayoutPass.cpp.
References mlir::applyFullConversion(), mlir::failed(), mlir::OwningRewritePatternList::insert(), and mlir::VulkanLayoutUtils::isLegalType().