MLIR: mlir::linalg::detail Namespace Reference
mlir::linalg::detail Namespace Reference
Functions
LogicalResult verifyStructuredOpInterface (Operation *op)
Function Documentation
verifyStructuredOpInterface()
LogicalResult mlir::linalg::detail::verifyStructuredOpInterface (Operation * op)
Definition at line 386 of file LinalgOps.cpp.
References mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), getElementType(), mlir::Block::getNumArguments(), mlir::Operation::getNumResults(), mlir::AffineMap::getResults(), mlir::Operation::getResultTypes(), mlir::BlockArgument::getType(), mlir::isDenseDim(), mlir::Type::isIndex(), mlir::isSparseDim(), mlir::ArrayAttr::size(), mlir::success(), mlir::verify(), verify(), and mlir::OpTrait::impl::verifyAtLeastNOperands().