MLIR: mlir::tensor Namespace Reference
mlir::tensor Namespace Reference
Functions
bool canFoldIntoConsumerOp (CastOp castOp)
Determines whether tensor::CastOp casts to a more dynamic version of the source tensor.
Function Documentation
canFoldIntoConsumerOp()
bool mlir::tensor::canFoldIntoConsumerOp (CastOp castOp)
Determines whether tensor::CastOp casts to a more dynamic version of the source tensor.
This is useful to fold a tensor.cast into a consuming op and implement canonicalization patterns for ops in different dialects that may consume the results of tensor.cast operations. Such foldable tensor.cast operations are typically inserted as subtensor ops and are canonicalized, to preserve the type compatibility of their uses.
Returns true when all conditions are met:
source and result are ranked tensors with same element type and rank.
the tensor type has more static information than the result
Example:
%1 = tensor.cast %0 : tensor<8x16xf32> to tensor<?x?xf32>
%2 = consumer %1 ... : tensor<?x?xf32> ...
folds into:
%2 = consumer %0 ... : tensor<8x16xf32> ...
Definition at line 44 of file TensorOps.cpp.
References mlir::Type::dyn_cast(), mlir::impl::foldCastOp(), mlir::ShapedType::getElementType(), mlir::RankedTensorType::getShape(), mlir::ShapedType::isDynamic(), mlir::succeeded(), and mlir::verifyCompatibleShape().