MLIR: lib/Conversion/SCFToSPIRV/SCFToSPIRV.cpp File Reference
SCFToSPIRV.cpp File Reference
#include "mlir/Conversion/SCFToSPIRV/SCFToSPIRV.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/IR/BuiltinOps.h"
Classes
struct mlir::ScfToSPIRVContextImpl
Namespaces
mlir
Include the generated interface declarations.
Functions
template<typename ScfOp , typename OpTy >
static void replaceSCFOutputValue (ScfOp scfOp, OpTy newOp, SPIRVTypeConverter &typeConverter, ConversionPatternRewriter &rewriter, ScfToSPIRVContextImpl *scfToSPIRVContext, ArrayRef< Type > returnTypes)
Helper function to replaces SCF op outputs with SPIR-V variable loads.
Function Documentation
replaceSCFOutputValue()
template<typename ScfOp , typename OpTy > static void replaceSCFOutputValue (ScfOp scfOp, OpTy newOp, SPIRVTypeConverter & typeConverter, ConversionPatternRewriter & rewriter, ScfToSPIRVContextImpl * scfToSPIRVContext, ArrayRef< Type > returnTypes) static
Helper function to replaces SCF op outputs with SPIR-V variable loads.
We create VariableOp to handle the results value of the control flow region. spv.loop/spv.selection currently don't yield value. Right after the loop we load the value from the allocation and use it as the SCF op result.
Definition at line 92 of file SCFToSPIRV.cpp.
References mlir::ConversionPatternRewriter::applySignatureConversion(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::ConversionPatternRewriter::eraseOp(), mlir::Block::front(), mlir::spirv::PointerType::get(), mlir::Builder::getI1Type(), mlir::Builder::getI32IntegerAttr(), mlir::OpBuilder::getInsertionBlock(), mlir::Block::getNumArguments(), mlir::Block::getTerminator(), mlir::BlockArgument::getType(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::ScfToSPIRVContextImpl::outputVars, mlir::TypeConverter::SignatureConversion::remapInput(), mlir::ConversionPatternRewriter::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().