MLIR: lib/Target/SPIRV/Serialization.cpp File Reference
Serialization.cpp File Reference
#include "mlir/Target/SPIRV/Serialization.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/RegionGraphTraits.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Target/SPIRV/SPIRVBinaryUtils.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/bit.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVSerialization.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "spirv-serialization"
#define GET_SERIALIZATION_FNS
Functions
static LogicalResult encodeInstructionInto (SmallVectorImpl< uint32_t > &binary, spirv::Opcode op, ArrayRef< uint32_t > operands)
Encodes an SPIR-V instruction with the given opcode and operands into the given binary vector.
static LogicalResult visitInPrettyBlockOrder (Block *headerBlock, function_ref< LogicalResult(Block *)> blockHandler, bool skipHeader=false, BlockRange skipBlocks={})
A pre-order depth-first visitor function for processing basic blocks.
static Block * getStructuredControlFlowOpMergeBlock (Operation *op)
Returns the merge block if the given op is a structured control flow op.
static Block * getPhiIncomingBlock (Block *block)
Given a predecessor block for a block with arguments, returns the block that should be used as the parent block for SPIR-V OpPhi instructions corresponding to the block arguments.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-serialization"
Definition at line 34 of file Serialization.cpp.
GET_SERIALIZATION_FNS
#define GET_SERIALIZATION_FNS
Definition at line 2157 of file Serialization.cpp.
Function Documentation
encodeInstructionInto()
static LogicalResult encodeInstructionInto (SmallVectorImpl< uint32_t > & binary, spirv::Opcode op, ArrayRef< uint32_t > operands) static
Encodes an SPIR-V instruction with the given opcode and operands into the given binary vector.
Definition at line 40 of file Serialization.cpp.
References mlir::spirv::getPrefixedOpcode(), and mlir::success().
Referenced by getPhiIncomingBlock().
getPhiIncomingBlock()
static Block* getPhiIncomingBlock (Block * block) static
Given a predecessor block for a block with arguments, returns the block that should be used as the parent block for SPIR-V OpPhi instructions corresponding to the block arguments.
Definition at line 93 of file Serialization.cpp.
References mlir::spirv::appendModuleHeader(), mlir::Block::args_empty(), mlir::Block::back(), mlir::Block::begin(), mlir::Type::cast(), mlir::spirv::StructType::MemberDecorationInfo::decoration, mlir::spirv::StructType::MemberDecorationInfo::decorationValue, mlir::Attribute::dyn_cast(), mlir::Value::dyn_cast(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::Operation::emitError(), encodeInstructionInto(), mlir::spirv::encodeStringLiteralInto(), mlir::Block::end(), mlir::failed(), mlir::failure(), mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::Block::getArgument(), mlir::Operation::getAttr(), mlir::Operation::getAttrOfType(), mlir::Operation::getAttrs(), mlir::Operation::getBlock(), mlir::Type::getContext(), mlir::Value::getDefiningOp(), getElementType(), mlir::FileLineColLoc::getFilename(), mlir::spirv::StructType::getIdentified(), mlir::spirv::StructType::getIdentifier(), mlir::FunctionType::getInputs(), mlir::IntegerAttr::getInt(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::Operation::getName(), mlir::Block::getNumArguments(), mlir::FunctionType::getNumResults(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::Block::getParentOp(), mlir::Block::getPredecessors(), mlir::FunctionType::getResult(), mlir::Operation::getResult(), getStructuredControlFlowOpMergeBlock(), mlir::SymbolTable::getSymbolAttrName(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::BlockArgument::getType(), mlir::ElementsAttr::getType(), mlir::ArrayAttr::getValue(), mlir::FloatAttr::getValue(), mlir::IntegerAttr::getValue(), mlir::BoolAttr::getValue(), mlir::FlatSymbolRefAttr::getValue(), mlir::spirv::StructType::MemberDecorationInfo::hasValue, mlir::Type::isa(), mlir::Block::isEntryBlock(), mlir::spirv::StructType::isIdentified(), mlir::spirv::kHeaderWordCount, mlir::spirv::StructType::MemberDecorationInfo::memberIndex, mlir::Block::print(), mlir::Operation::result_type_begin(), mlir::spirv::serialize(), mlir::ArrayAttr::size(), mlir::succeeded(), mlir::success(), and visitInPrettyBlockOrder().
getStructuredControlFlowOpMergeBlock()
static Block* getStructuredControlFlowOpMergeBlock (Operation * op) static
Returns the merge block if the given op is a structured control flow op.
Otherwise returns nullptr.
Definition at line 82 of file Serialization.cpp.
Referenced by getPhiIncomingBlock().
visitInPrettyBlockOrder()
static LogicalResult visitInPrettyBlockOrder (Block * headerBlock, function_ref< LogicalResult(Block *)> blockHandler, bool skipHeader = false, BlockRange skipBlocks = {}) static
A pre-order depth-first visitor function for processing basic blocks.
Visits the basic blocks starting from the given headerBlock in pre-order depth-first manner and calls blockHandler on each block. Skips handling blocks in the skipBlocks list. If skipHeader is true, blockHandler will not be invoked in headerBlock but still handles all headerBlock's successors.
SPIR-V spec "2.16.1. Universal Validation Rules" requires that "the order of blocks in a function must satisfy the rule that blocks appear before all blocks they dominate." This can be achieved by a pre-order CFG traversal algorithm. To make the serialization output more logical and readable to human, we perform depth-first CFG traversal and delay the serialization of the merge block and the continue block, if exists, until after all other blocks have been processed.
Definition at line 65 of file Serialization.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by getPhiIncomingBlock().