MLIR: lib/Dialect/Linalg/Transforms/Tiling.cpp File Reference
Tiling.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/CommandLine.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define DEBUG_TYPE "linalg-tiling"
#define GET_OP_LIST
#define GET_OP_LIST
Typedefs
using folded_affine_min = FoldedValueBuilder< AffineMinOp >
using LoopIndexToRangeIndexMap = DenseMap< int, int >
Functions
static bool isZero (Value v)
static std::tuple< SmallVector< Range, 4 >, LoopIndexToRangeIndexMap > makeTiledLoopRanges (OpBuilder &b, Location loc, AffineMap map, ValueRange allShapeSizes, ValueRange allTileSizes)
static void transformIndexedGenericOpIndices (OpBuilder &b, LinalgOp op, SmallVectorImpl< Value > &ivs, const LoopIndexToRangeIndexMap &loopIndexToRangeIndex)
static bool isTiled (AffineExpr expr, ValueRange tileSizes)
static bool isTiled (AffineMap map, ValueRange tileSizes)
static SmallVector< Value, 4 > makeTiledShapes (OpBuilder &b, Location loc, LinalgOp linalgOp, ValueRange operands, AffineMap map, ValueRange ivs, ValueRange tileSizes, ValueRange allShapeSizes)
template<typename LoopTy >
static Optional< TiledLinalgOp > tileLinalgOpImpl (OpBuilder &b, LinalgOp op, ValueRange tileSizes, const LinalgTilingOptions &options)
template<typename LoopTy >
static Optional< TiledLinalgOp > tileLinalgOpImpl (OpBuilder &b, LinalgOp op, const LinalgTilingOptions &options)
static void insertTilingPatterns (OwningRewritePatternList &patterns, const LinalgTilingOptions &options, MLIRContext *ctx)
Populate the given list with patterns that apply Linalg tiling.
static void applyTilingToLoopPatterns (LinalgTilingLoopType loopType, FuncOp funcOp, ArrayRef< int64_t > tileSizes)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-tiling"
Definition at line 39 of file Tiling.cpp.
GET_OP_LIST [1/2]
#define GET_OP_LIST
GET_OP_LIST [2/2]
#define GET_OP_LIST
Typedef Documentation
folded_affine_min
using folded_affine_min = FoldedValueBuilder<AffineMinOp>
Definition at line 37 of file Tiling.cpp.
LoopIndexToRangeIndexMap
using LoopIndexToRangeIndexMap = DenseMap<int, int>
Definition at line 47 of file Tiling.cpp.
Function Documentation
applyTilingToLoopPatterns()
static void applyTilingToLoopPatterns (LinalgTilingLoopType loopType, FuncOp funcOp, ArrayRef< int64_t > tileSizes) static
Definition at line 583 of file Tiling.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::linalg::getLinalgTilingCanonicalizationPatterns(), insertTilingPatterns(), options, mlir::linalg::LinalgTilingOptions::setLoopType(), and mlir::linalg::LinalgTilingOptions::setTileSizes().
insertTilingPatterns()
static void insertTilingPatterns (OwningRewritePatternList & patterns, const LinalgTilingOptions & options, MLIRContext * ctx) static
Populate the given list with patterns that apply Linalg tiling.
Definition at line 574 of file Tiling.cpp.
Referenced by applyTilingToLoopPatterns().
isTiled() [1/2]
static bool isTiled (AffineExpr expr, ValueRange tileSizes) static
Definition at line 204 of file Tiling.cpp.
Referenced by isTiled(), makeTiledLoopRanges(), and makeTiledShapes().
isTiled() [2/2]
static bool isTiled (AffineMap map, ValueRange tileSizes) static
Definition at line 213 of file Tiling.cpp.
References mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), and isTiled().
isZero()
static bool isZero (Value v) static
Definition at line 41 of file Tiling.cpp.
References mlir::Value::getDefiningOp().
Referenced by addSuspensionPoint(), makeTiledLoopRanges(), makeTiledShapes(), and tileLinalgOpImpl().
makeTiledLoopRanges()
static std::tuple<SmallVector<Range, 4>, LoopIndexToRangeIndexMap> makeTiledLoopRanges (OpBuilder & b, Location loc, AffineMap map, ValueRange allShapeSizes, ValueRange allTileSizes) static
Definition at line 59 of file Tiling.cpp.
References applyMapToValues(), mlir::AffineExpr::cast(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineMap::getNumResults(), mlir::AffineDimExpr::getPosition(), mlir::AffineBinaryOpExpr::getRHS(), isTiled(), isZero(), and mlir::Mul.
Referenced by tileLinalgOpImpl().
makeTiledShapes()
static SmallVector<Value, 4> makeTiledShapes (OpBuilder & b, Location loc, LinalgOp linalgOp, ValueRange operands, AffineMap map, ValueRange ivs, ValueRange tileSizes, ValueRange allShapeSizes) static
Definition at line 223 of file Tiling.cpp.
References applyMapToValues(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::ShapedType::getDimSize(), mlir::Builder::getIndexType(), mlir::ShapedType::getRank(), mlir::AffineMap::getSubMap(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), isTiled(), and isZero().
Referenced by tileLinalgOpImpl().
tileLinalgOpImpl() [1/2]
template<typename LoopTy > static Optional<TiledLinalgOp> tileLinalgOpImpl (OpBuilder & b, LinalgOp op, ValueRange tileSizes, const LinalgTilingOptions & options) static
Definition at line 319 of file Tiling.cpp.
References applyMapToValues(), mlir::linalg::applyPermutationToVector(), mlir::OpBuilder::create(), mlir::linalg::LinalgTilingOptions::distribution, mlir::detail::enumerate(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::edsc::ScopedContext::getLocation(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::AffineMap::getPermutationMap(), mlir::Operation::getResults(), mlir::linalg::LinalgTilingOptions::interchangeVector, mlir::inversePermutation(), isZero(), makeTiledLoopRanges(), makeTiledShapes(), and transformIndexedGenericOpIndices().
tileLinalgOpImpl() [2/2]
template<typename LoopTy > static Optional<TiledLinalgOp> tileLinalgOpImpl (OpBuilder & b, LinalgOp op, const LinalgTilingOptions & options) static
Definition at line 471 of file Tiling.cpp.
References options, mlir::OpBuilder::setInsertionPoint(), and mlir::linalg::LinalgTilingOptions::tileSizeComputationFunction.
transformIndexedGenericOpIndices()
static void transformIndexedGenericOpIndices (OpBuilder & b, LinalgOp op, SmallVectorImpl< Value > & ivs, const LoopIndexToRangeIndexMap & loopIndexToRangeIndex) static
Definition at line 165 of file Tiling.cpp.
References mlir::OpBuilder::create(), mlir::Value::getDefiningOp(), mlir::Value::getUses(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by tileLinalgOpImpl().